### ISSUE TITLE
Practica 2 Visual Studio UI

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipoolaxd#1]
[practica 2 INTERFAZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipoolaxd/files/14314204/practica.2.INTERFAZ.pdf)

**Comment by ArcangelGC** [comment]
Buenos días.
Calificación. 85
Porcentaje: 17%

Comentarios:

Favor de ponerle un indicie, para saber el orden y el contenido del documento.

Agregar más imágenes para hacer una idea más clara de cada cosa.

Nuevamente, centrar el texto para que el trabajo se vea más profesional.

Gracias:)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
